security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # usado para recarregar o usuário da sessão e outras funcionalidades (ex: switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login  # Página de login na rota '/login'
                check_path: app_login
                # Redireciona para /home após login bem-sucedido
                success_handler: App\Security\LoginSuccessHandler
                enable_csrf: true
                default_target_path: home 
            logout:
                path: app_logout
                target: app_login 


    # Controle de acesso para proteger rotas
    access_control:
        - { path: ^/home, roles: ROLE_USER }  # Exige que o usuário esteja autenticado para acessar qualquer rota que comece com /home

when@test:
    security:
        password_hashers:
            # Configurações de hash de senha para testes (otimizadas para ser menos intensivas em recursos)
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4    # Valor mais baixo para bcrypt
                time_cost: 3  # Valor mais baixo para argon2
                memory_cost: 10  # Valor mais baixo para argon2
